### ISSUE TITLE
Jobs Stuck In 'Enqueued' State

### ISSUE THREAD

**Issue by nickmistretta9** [sergeyzwezdin/Hangfire.Mongo#180] opened 2019-03-20 18:28 UTC
I am getting an issue where multiple jobs will be in the Enqueued state, but never make it out of there. When I click on the queue in the dashboard, it shows no jobs to be found, even though there is a number of them showing. In Atlas, when I query for `{StateName:"Enqueued"}`, it shows those n jobs that are stuck. The jobs are enqueued every minute from a recurring job setup, which is set up to loop through a number of objects, and enqueue subsequent job for each one, like such:

```
public void ProcessCallbacks() {
  var objects = repo.GetCallbacks();
  foreach(var object in objects) {
    BackgroundJob.Schedule(() => Processor(object.ID), DateTime.Now);
  }
}
```

This happens randomly, there doesn't seem to be any specific date or time that causes it to get stuck like that. Most of the time it runs fine, but there are usually ~5-10 each night that cause this to happen. Could this be a worker issue not being able to pick up a job because all workers are in use, which causes it to get stuck?

Any help into this would be greatly appreciated.

**Comment by gottscj** [comment] 2019-03-20 19:22
@nickmistretta9 ,

Would it be possible to attach some info about the stuck job? I especially interested in
JobQueueDto's still in the queue.
Below is from memory so it might be faulty ¯\_(ツ)_/¯

{ "$and": [{ "_t": "JobQueueDto"},  { "FetchedAt", {"$ne": null} }] }

Also try to query JobQueueDto's by the stuck jobs "JobId", see if its been fetched.
Also all writes are logged to hangfire's logging system as DEBUG, you could attach a logger:
http://docs.hangfire.io/en/latest/configuration/configuring-logging.html

if the data is not too sensitive, I would love to take a look at it.

Meanwhile looking your snippet, it should be possible to reproduce locally, I will try to reproduce locally.

**Comment by nickmistretta9** [comment] 2019-03-21 13:32
@gottscj Thanks for your response! When I query for "JobQueueDto" I am getting no results from the `hangfire.jobGraph` DB. I filtered by `{StateName:"Enqueued"}` to get the list of jobs that are "stuck" in the enqueued state and here is an example of one of the response objects:

```
{
    "_id":objectId(5c8c3e24ee0a523becca8123),
    "_t": Array [
        0:"BaseJobDto",
        1:"ExpiringJobDto",    
        2:"JobDto"
    ],
    "ExpireAt":null,
    "StateName":"Enqueued",
    "InvocationData":"{"Type":"SPPC_Jobs.Controllers.SCPController, SPPC_Jobs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Method":"ProcessIncomingCallbacks","ParameterTypes":"[]","Arguments":"[]"}",
    "Arguments":"[]",
    "Parameters":Object {
        RecurringJobId:""SCPController.ProcessIncomingCallbacks""
        CurrentCulture:""en-US""
        CurrentUICulture:""en-US""
    },
    "StateHistory":Array [
        0:Object {
            Name:"Enqueued",
            Reason:"Triggered by recurring job scheduler",
            CreatedAt:2019-03-16T00:07:00.834+00:00,
            Data:Object {
                EnqueuedAt:"2019-03-16T00:07:00.7724447Z",
                Queue:"scp"
            }
        }
    ],
    "CreatedAt":2019-03-16T00:07:00.772+00:00
}
```
I am going to attach a logger and see what I can get out of it, but let me know if this is helpful in the meantime!

**Comment by gottscj** [comment] 2019-03-22 18:43
@nickmistretta9 ,

Can you query the JobQueueDto object by the JobId you showed above? Im wondering if the job is actually run, but the state is not updated.
Looking at the Job you show above it seems to be a recurrent job, but the loop in your first post its a scheduled job.
Do you see a pattern in the stuck jobs in regards with how its scheduled?

Thanks!

**Comment by gottscj** [comment] 2019-03-25 10:03
@nickmistretta9,

I am able to reproduce locally. It seems to be related to a lock timing out. if you wait 90s the lock is droppet and tried again. I am looking into why its not able to acquire the lock

**Comment by nickmistretta9** [comment] 2019-03-25 13:40
@gottscj Hey sorry for the delay in my response! So that first loop is called by another recurring method, like so:

```
var scpController = new SCPController();
RecurringJob.AddOrUpdate(() => scpController.ProcessIncomingCallbacks(), Cron.Minutely());
```

Which database would the `JobQueueDto` appear in? When I query `hangfire.jobGraph`, the only object that shows up for that JobID is the one that I linked above.

**Comment by gottscj** [comment] 2019-03-25 20:03
@nickmistretta9,

The JobQueueDto lives in the jobgraph. But only while the job is being processed.

I figured it out. There is not a bug per se. and your job _will_ be processed. Our wait times is be bit out of date, compared to SqlServer implementation. If the distributed lock fails to acquire a lock it will wait the timeout given by Hangfire.Core / 10.

Hangfire.Core gives a timeout of 900000 ms. divided by 10 that gives 90000ms eg. 90 seconds before the job is processed. Looking at the Hangfire.SqlServer implementation. The timeout is divided by 1000 which gives 900 ms.

So. All your jobs will be processed with v0.5.15. 
You will just have to wait 90 seconds if the job is re-queued or the lock is somehow not aquired in first attempt.

for 0.6.0, I will change the timeout to resemble whats done in the sql server implementation.
and ultimately use tailable cursors to signal when the lock can be released.

**Comment by nickmistretta9** [comment] 2019-03-25 21:12
@gottscj Ok great thank you for that information! So even if the job is processed after 90 seconds, will this new implementation remove them from the database upon completion? We are trying to also ensure that should these jobs timeout or not be picked up by the lock that in the dashboard/database we won't have a "queue" with however many jobs timed out.

**Comment by gottscj** [comment] 2019-03-26 08:53
@nickmistretta9,

I apologize I was a bit unclear. 
The actual job is not "stuck" in 90s. Its executed as fast as possible. Its the job data Update which is stuck. eg. changing the state from "Enqueued" to "Processing" and then to "Succeeded" (or "Failed").

The enqueued jobs are not executed under lock, only updating the state data. So the information in the dashboard is not showing the correct information while the lock waits for access.

**Comment by gottscj** [comment] 2019-05-01 20:16
Should be resolved in 0.6.0, please let me know if it doesnt work as expected.

**Comment by KyleCraviotto** [comment] 2019-10-31 14:21
I'm continuing to see this issue in 0.6.4
i'm not sure what details you need, but we are queuing up around 900 jobs and once they are finished they queue themselves up again. It seems random, but the jobs get stuck and don't process, or only process 4-5 at a time instead of the usual 35.

**Comment by gottscj** [comment] 2019-11-04 09:19
@KyleCraviotto,

Sorry, for late reply.

logs are always helpful. The job is enqueuing itself after a succesful run? is it scheduled by a cron or as fast as possible?

How do you see this information? in the dashboard? can you confirm the job is not actually run or its the monitoring api which is lagging?

thanks

**Comment by Kronos11** [comment] 2019-11-04 18:09
@gottscj 
Here's the gist of how we are using hangfire. 

Step 1) We run a recurring job every 15 minutes that queues up a bunch (up to 800) of background jobs. This job also makes sure we are not queuing up duplicate jobs and we are deleting any duplicate jobs that may have been created as well.

Step 2) Each background job runs after 3 minutes, does it's processing and then kicks off another background job of itself.

This continues usually for anywhere from 2-24 hours and then we notice that the number of queues jobs goes up and up, and usually stacks up to 700ish, while the processing jobs goes down and down usually in the 8 or so range.

I see this both in the hangfire dashboard and it the database itself.

**Comment by gottscj** [comment] 2019-11-07 09:46
@Kronos11,

Thanks for the update, I will try to reproduce.

**Comment by KyleCraviotto** [comment] 2019-12-05 19:35
We continued to have this issue so I switched to redis to see if that would resolve the issue and unfortunately it did not. I would guess this is some underlying hangfire issue, or a problem with our code.

**Comment by gottscj** [comment] 2019-12-06 15:47
@KyleCraviotto,

Sorry I didnt try this yet. Its been a little hectic at my end. I will still try to reproduce it, to see if I can figure out what the problem is. If its a hangfire issue, we can add a ticket in that project

**Comment by spoofer213** [comment] 2020-04-22 19:56
Hello guys! I get similar bug. My recurring jobs stuck in "Enqueued" state and dont run. They are executed only after restart application, but new jobs stuck again in "Enqueued" state.
My recurring job
![image](https://user-images.githubusercontent.com/17124926/80026048-2bc89200-84ea-11ea-8863-ac5c19d62e05.png)

Stuck jobs
![image](https://user-images.githubusercontent.com/17124926/80026300-98dc2780-84ea-11ea-8e01-85b361901b0b.png)

Servers
![image](https://user-images.githubusercontent.com/17124926/80026467-d93ba580-84ea-11ea-806e-8c60a0fb3347.png)

Job in queue
![image](https://user-images.githubusercontent.com/17124926/80026720-43544a80-84eb-11ea-8352-0cfe18ccd25c.png)

Stack:
ASP.NET Core 3.1, MySql

Configuration:
![image](https://user-images.githubusercontent.com/17124926/80026902-8dd5c700-84eb-11ea-9294-6899f375495f.png)

Can anyone help with this problem?

**Closed** 2020-04-23 19:53 UTC
Labels: enhancement
