### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by rolfwessels** [sergeyzwezdin/Hangfire.Mongo#10] opened 2015-09-28 10:51 UTC
Hi,

I've used hanfire.mongo in a little project before and it works great. Thank you for the hard work.

I recently tried to use it again and I get a constant 100% cpu usage even though there are no processes running.

HangFire.Mongo version=0.2.2
mongocsharpdriver version=2.0.1

It seems that if I downgrade mongo and hangfire.mongo (no other changes). Then the problem goes away,
 
mongocsharpdriver version=1.9.2
HangFire.Mongo version=0.2.1

If you have some time could you please see if there is an easy fix to the issue.

Thanks

Rolf

**Comment by sergeyzwezdin** [comment] 2015-09-28 15:05
Thank you for your kind of word.
You are right. I noticed the same behavior by myself. The reason is `mongoscharpdriver` migrated to async API while HangFire still run everything synchronously. I used `AsyncHelper` to wrap async calls, but seems it increases CPU utilization. I will take a look when's possible to do with it when will have a spare minute and will release the fix.

**Comment by Thieund** [comment] 2015-09-30 03:35
Hi Sergeyzwezdin,
Could you please have a look at it now?  I really need this to be solve, and I cannot downgrade to previous version because I'm using mongoscharpdriver 2.x in many other places of my solution.
Thank you very much in advance.

**Comment by sergeyzwezdin** [comment] 2015-09-30 04:30
@Thieund I would suggest to use these options as a temprorary solution. Just pass your `MongoStorageOptions` object as third parameter for `GlobalConfiguration.Configuration.UseMongoStorage`.

**Comment by Thieund** [comment] 2015-09-30 04:32
Thank you for your quick response, Sergeyzwezdin.
I'll do that for now.

**Comment by rolfwessels** [comment] 2015-09-30 12:32
For now I will keep using the older version. Let us know when you have made the update. 

Thanks

**Comment by bluee** [comment] 2015-11-20 03:00
+1 Stuck with SQL Server until fixed :)

**Comment by sergeyzwezdin** [comment] 2015-12-06 09:13
Fixed in `v.0.2.3`, will be released soon.

**Closed by sergeyzwezdin** 2015-12-06 09:13 UTC
Labels: bug

**Comment by runxc1** [comment] 2015-12-07 17:02
Did migrating to the Mongo csharp 2.1 driver help to solve this issue or was it just changing how often the polling occurs?   I am curious as I have a site which is having high cpu utilization using the 2.0.1 driver and wondering if that could be part of the problem as this mentions that simply upgrading from 1.9 to 2.0 caused high cpu.

**Comment by sergeyzwezdin** [comment] 2015-12-08 04:23
@runxc1 it isn't reated to mongo driver. In previous version, after I upgraded Hangfire version I forgot to initialize some parameters. As a result loop interated quite often, which made high CPU utilization :-)
Fix for that described here - https://github.com/sergeyzwezdin/Hangfire.Mongo/commit/1586862b7059f6448f11ab3895d6507271ab7a04
But actually I checked mostly everything in code to find root cause. Thank you to profilers :-)
