### ISSUE TITLE
when init hangfire mongodb requires migration

### ISSUE THREAD

**Issue by Caskia** [sergeyzwezdin/Hangfire.Mongo#185] opened 2019-05-09 13:12 UTC
Version: 0.6.0
when first time initialize the database(not upgrade database), it will throw the require migration exception.

**Comment by gottscj** [comment] 2019-05-09 18:33
@Caskia,


We need you to input what you want to do if a migration is needed. By default we will throw an exception if you havent set the migration strategy.

We should probably be address this, as this shouldnt be needed when there is no db to begin with. :)
I recommend you set the migration options like this if you just are trying it out
`
var migrationOptions = new MongoStorageOptions
{
      MigrationOptions = new MongoMigrationOptions
       {
             Strategy = MongoMigrationStrategy.Drop,
              BackupStrategy = MongoBackupStrategy.None
        }
 };
`

**Comment by Caskia** [comment] 2019-05-10 04:06
Hi gottscj:
I know your migration rule. What I want to express is that there is no database, when we start use this first time, it throws this exception in this new version(0.6.0). The previous version does not.

**Comment by bogdanmarin** [comment] 2019-05-12 19:14
Same here, this is very critical to us. It seems if there is no database it does not start. please provide a fix for this.

**Comment by bogdanmarin** [comment] 2019-05-12 19:19
Application: 
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: MongoDB.Driver.MongoCommandException
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ProcessResponse(MongoDB.Driver.Core.Connections.ConnectionId, MongoDB.Driver.Core.WireProtocol.Messages.CommandMessage)
   at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Execute(MongoDB.Driver.Core.Connections.IConnection, System.Threading.CancellationToken)
   at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Execute(MongoDB.Driver.Core.Connections.IConnection, System.Threading.CancellationToken)
   at MongoDB.Driver.Core.Servers.Server+ServerChannel.ExecuteProtocol[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](MongoDB.Driver.Core.WireProtocol.IWireProtocol`1<System.__Canon>, System.Threading.CancellationToken)
   at MongoDB.Driver.Core.Servers.Server+ServerChannel.Command[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](MongoDB.Driver.Core.Bindings.ICoreSession, MongoDB.Driver.ReadPreference, MongoDB.Driver.DatabaseNamespace, MongoDB.Bson.BsonDocument, System.Collections.Generic.IEnumerable`1<MongoDB.Driver.Core.WireProtocol.Messages.Type1CommandMessageSection>, MongoDB.Bson.IO.IElementNameValidator, MongoDB.Bson.BsonDocument, System.Action`1<MongoDB.Driver.Core.WireProtocol.Messages.Encoders.IMessageEncoderPostProcessor>, MongoDB.Driver.Core.WireProtocol.CommandResponseHandling, MongoDB.Bson.Serialization.IBsonSerializer`1<System.__Canon>, MongoDB.Driver.Core.WireProtocol.Messages.Encoders.MessageEncoderSettings, System.Threading.CancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ExecuteProtocol(MongoDB.Driver.Core.Bindings.IChannelHandle, MongoDB.Driver.Core.Bindings.ICoreSessionHandle, MongoDB.Driver.ReadPreference, System.Threading.CancellationToken)
   at MongoDB.Driver.Core.Operations.CommandOperationBase`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ExecuteProtocol(MongoDB.Driver.Core.Bindings.IChannelSource, MongoDB.Driver.Core.Bindings.ICoreSessionHandle, MongoDB.Driver.ReadPreference, System.Threading.CancellationToken)
   at MongoDB.Driver.Core.Operations.WriteCommandOperation`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Execute(MongoDB.Driver.Core.Bindings.IWriteBinding, System.Threading.CancellationToken)
   at MongoDB.Driver.Core.Operations.CreateCollectionOperation.Execute(MongoDB.Driver.Core.Bindings.IWriteBinding, System.Threading.CancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](MongoDB.Driver.Core.Bindings.IWriteBinding, MongoDB.Driver.Core.Operations.IWriteOperation`1<System.__Canon>, System.Threading.CancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.ExecuteWriteOperation[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](MongoDB.Driver.IClientSessionHandle, MongoDB.Driver.Core.Operations.IWriteOperation`1<System.__Canon>, System.Threading.CancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollectionHelper[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](MongoDB.Driver.IClientSessionHandle, System.String, MongoDB.Driver.CreateCollectionOptions`1<System.__Canon>, System.Threading.CancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(MongoDB.Driver.IClientSessionHandle, System.String, MongoDB.Driver.CreateCollectionOptions, System.Threading.CancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl+<>c__DisplayClass12_0.<CreateCollection>b__0(MongoDB.Driver.IClientSessionHandle)
   at MongoDB.Driver.MongoDatabaseImpl.UsingImplicitSession(System.Action`1<MongoDB.Driver.IClientSessionHandle>, System.Threading.CancellationToken)
   at MongoDB.Driver.MongoDatabaseImpl.CreateCollection(System.String, MongoDB.Driver.CreateCollectionOptions, System.Threading.CancellationToken)
   at Hangfire.Mongo.Migration.Steps.Version17.AddNotificationsCollection.Execute(MongoDB.Driver.IMongoDatabase, Hangfire.Mongo.MongoStorageOptions, Hangfire.Mongo.Migration.IMongoMigrationContext)
   at Hangfire.Mongo.Migration.MongoMigrationRunner.Execute(Hangfire.Mongo.MongoSchema, Hangfire.Mongo.MongoSchema)

Exception Info: Hangfire.Mongo.Migration.MongoMigrationException
   at Hangfire.Mongo.Migration.MongoMigrationRunner.Execute(Hangfire.Mongo.MongoSchema, Hangfire.Mongo.MongoSchema)
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategyDrop.Migrate(Hangfire.Mongo.MongoSchema, Hangfire.Mongo.MongoSchema)
   at Hangfire.Mongo.Migration.Strategies.MongoMigrationStrategyBase.Execute(Hangfire.Mongo.MongoSchema, Hangfire.Mongo.MongoSchema)
   at Hangfire.Mongo.Migration.MongoMigrationManager.Migrate()
   at Hangfire.Mongo.Migration.MongoMigrationManager.MigrateIfNeeded(Hangfire.Mongo.MongoStorageOptions, MongoDB.Driver.IMongoDatabase)
   at Hangfire.Mongo.MongoStorage..ctor(MongoDB.Driver.MongoClientSettings, System.String, Hangfire.Mongo.MongoStorageOptions)
   at 
Hangfire.GlobalConfigurationExtensions.UseMongoStorage(Hangfire.IGlobalConfiguration, Hangfire.Mongo.MongoMigrationOptions)
   at 
Hangfire.HangfireExtensions.RegisterHangfire(SimpleInjector.Container)
   at ...

**Comment by gottscj** [comment] 2019-05-12 19:27
@bogdanmarin 

what driver version are you using? Im trying this now on Mongo v4.0.3 and I cant reproduce

**Comment by bogdanmarin** [comment] 2019-05-12 19:36
We are using Hangfire.MongoDb 0.6.0, MongoDB.Driver 2.8.0.

**Comment by gottscj** [comment] 2019-05-12 19:38
Could you add some more information?

what is your setup? its a fresh db? do you have multiple instances of hangfire running? everything you can think of. you are not giving me much to work with..

**Comment by gottscj** [comment] 2019-05-12 19:41
also please add logging:

`config.UseColouredConsoleLogProvider(LogLevel.Trace);`

Please also try the asp-net-core sample and see if you get the same error. is the mongo db version 4.0.3 or the newest 4.0.9?

**Comment by bogdanmarin** [comment] 2019-05-12 19:41
Yes, so we have a fresh db, Mongo is v4, Driver is 2.8.0 and your lib is 0.6.0 and we recently upgraded to 0.6.0 and sudently our service is not starting anymore.

We are using these strategies:

new MongoMigrationOptions
        {
            Strategy = MongoMigrationStrategy.Drop,
            BackupStrategy = MongoBackupStrategy.None,
        };

**Comment by bogdanmarin** [comment] 2019-05-12 19:46
MongoDB is 4.0.4

**Comment by bogdanmarin** [comment] 2019-05-12 19:49
It seems we get the same error even with Mongo DB 3.2,3.6 and 4.0.4.

**Comment by bogdanmarin** [comment] 2019-05-12 19:59
Any updates? Again I think @Caskia description is accurate. It throws exception when there is a first time initialization (no database). This never happened with prev version, it has to do with latest changes. The problem is that we cannot downgrade eather because then we will have the bug that hangs jobs in enqueued state present in the prev version so we are stuck now..

**Comment by gottscj** [comment] 2019-05-12 20:03
I just tried 4.0.9, the latest, I can't reproduce.

Could you try the latest version.
Please add the logging, also please try the asp net core sample.

My understanding is that @Caskia, did not provide migration options. @Caskia, do you still get exceptions even if you add the migration options?

**Comment by gottscj** [comment] 2019-05-12 20:05
@bogdanmarin ,

You can use 0.5.15, the enqueued job bug is only for the monitoring api. the actual job is executed.

**Comment by Caskia** [comment] 2019-05-14 02:18
@gottscj 
If use migration options, won't get the errors.
But when use previous version there is no need to use migration options at first time initialization(database)

**Comment by gottscj** [comment] 2019-05-16 08:48
@Caskia,

For an empty db we are actually running all migrations. I Personally think that explicitly stating how you want to handle migrations is better than a default setting which you might not have considered.

@bogdanmarin, Did you progress in your debugging?

**Comment by sameerAhmad9291** [comment] 2019-06-15 20:11
I am using **ASP.NET Core** I solved this problem by inserting below code in ConfigureServices function **Startup.cs** 

            var migrationOptions = new MongoMigrationOptions
            {
                Strategy = MongoMigrationStrategy.Drop,
                BackupStrategy = MongoBackupStrategy.None,
            };
            var storageOptions = new MongoStorageOptions
            {
                MigrationOptions = migrationOptions
            };
            services.AddHangfire(config =>
            {
                config.UseMongoStorage("mongodb://localhost", "application-database", storageOptions);
            });

**Comment by paulyipkh** [comment] 2019-06-28 04:00
I also encountered a similar problem when upgrade to v 0.6.1 with an exception 
MongoDB.Driver.MongoCommandException: 'Command createIndexes failed: Index with name: Resource already exists with different options.' on Hangfire start.

Strategy = MongoMigrationStrategy.Migrate,
BackupStrategy = MongoBackupStrategy.Collections

though it works if I drop the database and set the backup strategy to None

Strategy = MongoMigrationStrategy.Drop,
BackupStrategy = MongoBackupStrategy.None

but this is not feasible with a living database.

**Comment by gottscj** [comment] 2020-11-20 16:15
fixed

**Closed by gottscj** 2020-11-20 16:15 UTC
Labels: enhancement
