### ISSUE TITLE
Hangfire.Mongo.DistributedLock.MongoDistributedLockException: Could not release a lock on the resource 'HangFire:locks:schedulepoller'

### ISSUE THREAD

**Issue by RodrigoLimasss** [sergeyzwezdin/Hangfire.Mongo#61] opened 2017-04-13 10:45 UTC
Hi, I got this error using Hangfire.Mongo drive.

**Environment:**
- Win. Server 2012;
- 3 nodes of MongoDB with replication set;
- Hangfire.Pro: 1.4.7.0;
- Hangfire.Core: 1.6.8.0;
- Hangfire.Mongo: 0.3.2.201;

1000 jobs are executed every 15 min and 7 jobs at a time.

----
**Message:** Hangfire.Mongo.DistributedLock.MongoDistributedLockException: Could not release a lock on the resource 'HangFire:locks:schedulepoller': Check inner exception for details. System.UnauthorizedAccessException: Access to the path is denied.

**Exception:**
```
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.EventWaitHandle.OpenExistingWorker(String name, EventWaitHandleRights rights, EventWaitHandle& result)
   at Hangfire.Mongo.DistributedLock.MongoDistributedLock.Release()
   --- End of inner exception stack trace ---
   at Hangfire.Mongo.DistributedLock.MongoDistributedLock.Release()
   at Hangfire.Mongo.DistributedLock.MongoDistributedLock.Dispose()
   at Hangfire.Server.DelayedJobScheduler.EnqueueNextScheduledJob(BackgroundProcessContext context)
   at Hangfire.Server.DelayedJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)
```
----

I think the error happens in this line:
https://github.com/sergeyzwezdin/Hangfire.Mongo/blob/master/src/Hangfire.Mongo/DistributedLock/MongoDistributedLock.cs#L209

Someone had the same problem? 
Is there any solution for this?

Thanks.

**Comment by gottscj** [comment] 2017-05-10 19:08
@RodrigoLimasss,

Sorry for the late reply. 
I will try to replicate your issue and get back to you.

**Comment by MarLoe** [comment] 2017-09-02 11:20
@RodrigoLimasss, I have not been able to reproduce this. But I do have some good news. We are moving away from using **EventWaitHandle** - which is the root cause of the exception you are experiencing (as I read your issue report).

Look forward to the 0.6.0 release coming soon. You can get a sneak peak on the [signal](https://github.com/sergeyzwezdin/Hangfire.Mongo/tree/signal) branch.

**Comment by RodrigoLimasss** [comment] 2017-09-20 11:58
Hi @MarLoe, I'm waiting for the next version 0.6.0. 
Thanks

**Comment by MarLoe** [comment] 2017-09-21 09:36
@RodrigoLimasss, I am sorry to say that 0.6.0 has been delayed :(
After testing my new implementation that was targeted for 0.6.0, I found a couple of issues and some stability that need to be addressed before I will release.
I am releasing 0.5.3 today, that has some other improvements. Please try it out.

**Comment by gottscj** [comment] 2018-09-10 21:33
@RodrigoLimasss,

Is this still an issue? Else I will close this issue.

Thanks!

**Comment by provanguard** [comment] 2018-10-31 15:55
I have observed this new exception, apart from some other previously seen, that started appearing after the last 0.5.12 release:

```
2018-10-30T16:41:40.186084850Z 2018-10-30 16:41:40 ERR Unable to clean up locks on the resource 'Hangfire:locks:schedulepoller'. MongoDB.Driver.MongoConnectionException: An exception occurred while receiving a message from the server. ---> System.IO.IOException: Unable to read data from the transport connection: Connection timed out. ---> System.Net.Sockets.SocketException: Connection timed out
2018-10-30T16:41:40.186128450Z    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
2018-10-30T16:41:40.186134450Z    --- End of inner exception stack trace ---
2018-10-30T16:41:40.186149950Z    at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
2018-10-30T16:41:40.186154451Z    at MongoDB.Driver.Core.Misc.StreamExtensionMethods.ReadBytes(Stream stream, Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
2018-10-30T16:41:40.186158851Z    at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer()
2018-10-30T16:41:40.186163051Z    --- End of inner exception stack trace ---
2018-10-30T16:41:40.186166951Z    at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer()
2018-10-30T16:41:40.186170951Z    at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveBuffer(Int32 responseTo, CancellationToken cancellationToken)
2018-10-30T16:41:40.186175151Z    at MongoDB.Driver.Core.Connections.BinaryConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
2018-10-30T16:41:40.186197051Z    at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquiredConnection.ReceiveMessage(Int32 responseTo, IMessageEncoderSelector encoderSelector, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
2018-10-30T16:41:40.186202751Z    at MongoDB.Driver.Core.WireProtocol.CommandUsingCommandMessageWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
2018-10-30T16:41:40.186206951Z    at MongoDB.Driver.Core.WireProtocol.CommandWireProtocol`1.Execute(IConnection connection, CancellationToken cancellationToken)
2018-10-30T16:41:40.186216051Z    at MongoDB.Driver.Core.Servers.Server.ServerChannel.ExecuteProtocol[TResult](IWireProtocol`1 protocol, CancellationToken cancellationToken)
2018-10-30T16:41:40.186300051Z    at MongoDB.Driver.Core.Servers.Server.ServerChannel.Command[TResult](ICoreSession session, ReadPreference readPreference, DatabaseNamespace databaseNamespace, BsonDocument command, IEnumerable`1 commandPayloads, IElementNameValidator commandValidator, BsonDocument additionalOptions, Action`1 postWriteAction, CommandResponseHandling responseHandling, IBsonSerializer`1 resultSerializer, MessageEncoderSettings messageEncoderSettings, CancellationToken cancellationToken)
2018-10-30T16:41:40.186312651Z    at MongoDB.Driver.Core.Operations.RetryableWriteCommandOperationBase.ExecuteAttempt(RetryableWriteContext context, Int32 attempt, Nullable`1 transactionNumber, CancellationToken cancellationToken)
2018-10-30T16:41:40.186317252Z    at MongoDB.Driver.Core.Operations.RetryableWriteOperationExecutor.Execute[TResult](IRetryableWriteOperation`1 operation, RetryableWriteContext context, CancellationToken cancellationToken)
2018-10-30T16:41:40.186360052Z    at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.ExecuteBatches(RetryableWriteContext context, CancellationToken cancellationToken)
2018-10-30T16:41:40.186392252Z    at MongoDB.Driver.Core.Operations.BulkUnmixedWriteOperationBase`1.Execute(RetryableWriteContext context, CancellationToken cancellationToken)
2018-10-30T16:41:40.186403952Z    at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.ExecuteBatch(RetryableWriteContext context, Batch batch, CancellationToken cancellationToken)
2018-10-30T16:41:40.186465252Z    at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
2018-10-30T16:41:40.186471952Z    at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
2018-10-30T16:41:40.186508553Z    at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperation[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
2018-10-30T16:41:40.186540953Z    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
2018-10-30T16:41:40.186547353Z    at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
2018-10-30T16:41:40.186583153Z    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
2018-10-30T16:41:40.186589453Z    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, DeleteOptions options, Func`2 bulkWrite)
2018-10-30T16:41:40.186607653Z    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, DeleteOptions options, CancellationToken cancellationToken)
2018-10-30T16:41:40.186612753Z    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, CancellationToken cancellationToken)
2018-10-30T16:41:40.186616953Z    at Hangfire.Mongo.DistributedLock.MongoDistributedLock.Cleanup()
```

**Comment by gottscj** [comment] 2018-11-05 20:08
@provanguard,

Looking at the exception it looks like the connection to the DB is lost.

"Unable to read data from the transport connection: Connection timed out. ---> System.Net.Sockets.SocketException: Connection timed out"

Can you describe steps to reproduce this behavior?

Thanks!

**Comment by provanguard** [comment] 2018-11-05 20:17
@gottscj I wish I knew why this and other problems happen. They all seem to be caused by connection timeout. I don't know the reason for the timeout. I have 4 background jobs running at different intervals, from 2 to 60 minutes. I would get between 1 and 5 of these errors per day. The application is running in Azure and the database is mongo db running on AWS.

**Comment by provanguard** [comment] 2018-11-06 12:08
@gottscj How do I configure the mongo storage options to define a shorter timeout? It appears that for some strange reason connection to storage has issues on our system. Current timeout appears to be at 20 minutes, during which no jobs would be executed and it would finish with the exception I included above, after which jobs would resume as normal. I don't believe that there were actually connectivity issues to the mongo database that would last 20 minutes. So in summary there are at least 2 questions/issue here:
- How to configure timeout for Hangfire.Mongo?
- Why is the timeout happening and blocking all jobs from executing?

**Comment by gottscj** [comment] 2018-11-06 12:45
@provanguard,

You should be able to configure the mongo client exactly as you wish using the overloaded bootstrapper extension overload, which accepts a "MongoClientSettings" object. Please refer to the official mongo driver documentation: https://docs.mongodb.com/ecosystem/drivers/csharp/

Im not sure why the timeout is happening, I would recommend you to try to reproduce this in a local setup

**Comment by provanguard** [comment] 2018-11-06 13:06
I found the the way to configure the timeout (I assume). I will observe the results. 

```
BackgroundJobServerOptions serverOptions = new BackgroundJobServerOptions
{
      ServerTimeout = TimeSpan.FromMinutes(2)
};

app.UseHangfireServer(serverOptions);
```

**Comment by gottscj** [comment] 2018-11-06 19:14
@provanguard,
That is a Hangfire configuration and not a mongo configuration, but Hangfire might log something releveant.

**Comment by provanguard** [comment] 2018-11-07 08:40
Here is one more of the exceptions I am seeing, not only on the latest version:

```
2018-11-06T15:52:22.486600216Z 2018-11-06 15:52:22 ERR Unable to clean up locks on the resource 'Hangfire:locks:schedulepoller'. MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> System.ObjectDisposedException: Cannot access a disposed object.
2018-11-06T15:52:22.486641716Z Object name: 'System.Net.Sockets.Socket'.
2018-11-06T15:52:22.486646616Z    at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
2018-11-06T15:52:22.486706716Z    at MongoDB.Driver.Core.Connections.TcpStreamFactory.ConfigureConnectedSocket(Socket socket)
2018-11-06T15:52:22.486714316Z    at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateNetworkStream(Socket socket)
2018-11-06T15:52:22.486718416Z    at MongoDB.Driver.Core.Connections.TcpStreamFactory.CreateStream(EndPoint endPoint, CancellationToken cancellationToken)
2018-11-06T15:52:22.486767417Z    at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelper(CancellationToken cancellationToken)
2018-11-06T15:52:22.486775217Z    --- End of inner exception stack trace ---
2018-11-06T15:52:22.486779217Z    at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelper(CancellationToken cancellationToken)
2018-11-06T15:52:22.486841417Z    at MongoDB.Driver.Core.Connections.BinaryConnection.Open(CancellationToken cancellationToken)
2018-11-06T15:52:22.486848217Z    at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquiredConnection.Open(CancellationToken cancellationToken)
2018-11-06T15:52:22.486896617Z    at MongoDB.Driver.Core.Servers.Server.GetChannel(CancellationToken cancellationToken)
2018-11-06T15:52:22.486921518Z    at MongoDB.Driver.Core.Bindings.ServerChannelSource.GetChannel(CancellationToken cancellationToken)
2018-11-06T15:52:22.486925318Z    at MongoDB.Driver.Core.Bindings.ChannelSourceHandle.GetChannel(CancellationToken cancellationToken)
2018-11-06T15:52:22.486981418Z    at MongoDB.Driver.Core.Operations.RetryableWriteContext.Create(IWriteBinding binding, Boolean retryRequested, CancellationToken cancellationToken)
2018-11-06T15:52:22.487024918Z    at MongoDB.Driver.Core.Operations.BulkMixedWriteOperation.Execute(IWriteBinding binding, CancellationToken cancellationToken)
2018-11-06T15:52:22.487031318Z    at MongoDB.Driver.OperationExecutor.ExecuteWriteOperation[TResult](IWriteBinding binding, IWriteOperation`1 operation, CancellationToken cancellationToken)
2018-11-06T15:52:22.487093119Z    at MongoDB.Driver.MongoCollectionImpl`1.ExecuteWriteOperation[TResult](IClientSessionHandle session, IWriteOperation`1 operation, CancellationToken cancellationToken)
2018-11-06T15:52:22.487100519Z    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IClientSessionHandle session, IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
2018-11-06T15:52:22.487140619Z    at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
2018-11-06T15:52:22.487204819Z    at MongoDB.Driver.MongoCollectionImpl`1.BulkWrite(IEnumerable`1 requests, BulkWriteOptions options, CancellationToken cancellationToken)
2018-11-06T15:52:22.487212019Z    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, DeleteOptions options, Func`2 bulkWrite)
2018-11-06T15:52:22.487252219Z    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, DeleteOptions options, CancellationToken cancellationToken)
2018-11-06T15:52:22.487258519Z    at MongoDB.Driver.MongoCollectionBase`1.DeleteOne(FilterDefinition`1 filter, CancellationToken cancellationToken)
2018-11-06T15:52:22.487270420Z    at Hangfire.Mongo.DistributedLock.MongoDistributedLock.Cleanup()
```

It is somewhat hard to pinpoint where the issue originates from.

**Comment by gottscj** [comment] 2018-11-20 07:41
@provanguard,

from the exception it seems the underlying socket has been disposed by the MongoDb driver. Im guessing they would only do that if the network stream is closed.

**Comment by provanguard** [comment] 2018-11-22 11:41
@gottscj The errors I pasted above got solved after configuring more properties on the mongo repository client and the C# driver. Thanks for help!

**Comment by gottscj** [comment] 2018-11-23 08:32
@provanguard,

glad to hear it! :)

**Closed by gottscj** 2018-11-23 08:32 UTC
Labels: bug

**Comment by XGSleepWalker** [comment] 2019-06-12 08:52
@provanguard can you explain some of the properties you configured to make this error stop? I'm having this exact same problem and I'm a bit lost at what I should be looking at.

**Comment by provanguard** [comment] 2019-06-12 11:29
In Hangfire configuration:
```
var mongoclient = (IMongoClient)app.ApplicationServices.GetRequiredService(typeof(IMongoClient));
GlobalConfiguration.Configuration.UseMongoStorage(mongoclient.Settings, Settings.Database.DatabaseName, storageOptions);
```

In Mongo settings:
```
services.AddSingleton<IMongoClient>(provider =>
            {
                var settings = MongoClientSettings.FromUrl(MongoUrl.Create(Settings.Database.ConnectionString));
                settings.MaxConnectionPoolSize = 200;
                settings.MaxConnectionIdleTime = TimeSpan.FromMinutes(1);
                settings.ConnectTimeout = TimeSpan.FromSeconds(55);
                settings.SocketTimeout = TimeSpan.FromSeconds(55);
                return new MongoClient(settings);
            });
```

**Comment by williamtetlow** [comment] 2019-09-23 18:19
I'm posting here to elaborate a bit on @provanguard's solution.

I was having the same problem when the application was deployed to Azure but could not recreate locally and noticed that @provanguard was also having issues when deployed to Azure.

It looks like Azure will terminate inactive socket connections after 240ms. If the c# mongo clients timeouts are greater than 240ms this means that the connection would be terminated without the client being able to intercept it. Resulting in this exception.

So the fix is to ensure that the timeout is less than 240ms or increase the timeout in Azure (not recommended).

Suggested settings are 

````
settings.MaxConnectionIdleTime = TimeSpan.FromMinutes(1);
settings.ConnectTimeout = TimeSpan.FromSeconds(55);
settings.SocketTimeout = TimeSpan.FromSeconds(55);
````

https://stackoverflow.com/questions/34373003/connection-timeout-to-mongodb-on-azure-vm
https://stackoverflow.com/questions/25843963/mongodb-connection-timeout-when-mongodb-is-not-in-the-same-vm
